# Generated by Django 5.0 on 2026-03-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "ADMIN"), ("USER", "USER"), ("EDITOR", "EDITOR")],
                default="USER",
                max_length=50,
            ),
        ),
    ]
