# Generated by Django 5.2.13 on 2026-05-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('kk', 'Kazakh'), ('ru', 'Russian')], default='en', max_length=5),
        ),
    ]
