# Generated by Django 5.0 on 2026-05-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_reaction_type'),
        ('main', '0002_bookmark_and_more'),
    ]

    operations = [
    ]
