# Generated by Django 5.0 on 2026-05-14 15:43

from __future__ import annotations
from django.db import migrations, transaction
from django.utils.text import slugify
from datetime import datetime
import logging

# Use module logger so project logging configuration controls output
logger = logging.getLogger(__name__)

def make_unique_slug(model_cls, base_slug, pk=None, max_len=255):
    base = base_slug[:max_len]
    slug = base
    if pk is not None:
        conflict = model_cls.objects.filter(slug=slug).exclude(pk=pk).exists()
    else:
        conflict = model_cls.objects.filter(slug=slug).exists()
    i = 1
    while conflict:
        suffix = f"-{i}"
        allowed = max_len - len(suffix)
        candidate = base[:allowed] + suffix
        if pk is not None:
            conflict = model_cls.objects.filter(slug=candidate).exclude(pk=pk).exists()
        else:
            conflict = model_cls.objects.filter(slug=candidate).exists()
        if not conflict:
            slug = candidate
            break
        i += 1
    return slug

def forwards(apps, schema_editor):
    """Data migration to normalize existing slug fields.

    Notes:
    - This migration normalizes/sluggifies source fields and ensures uniqueness by
      appending numeric suffixes when necessary.
    - The migration intentionally does not implement an automatic `backwards` that
      restores previous slugs; rolling back should be done via DB backup if needed.
    - `unidecode` is imported lazily; if unavailable, fallback uses identity.
    """

    try:
        from unidecode import unidecode  # type: ignore
    except Exception:
        def unidecode(x: str) -> str:
            return x

    Category = apps.get_model("main", "Category")
    Tag = apps.get_model("main", "Tag")
    Article = apps.get_model("main", "Article")

    targets = [
        (Category, "name", 255),
        (Tag, "name", 255),
        (Article, "title", 255),
    ]

    with transaction.atomic():
        for model_cls, source_field, max_len in targets:
            qs = model_cls.objects.all().order_by("pk")
            for obj in qs:
                source = getattr(obj, source_field, "") or ""
                base = slugify(unidecode(source)).strip("-")
                if not base:
                    base = f"item-{obj.pk}"
                new_slug = make_unique_slug(model_cls, base, pk=obj.pk, max_len=max_len)
                old_slug = getattr(obj, "slug", None)
                if old_slug != new_slug:
                    logger.info("PK=%s model=%s old=%r new=%r", obj.pk, model_cls.__name__, old_slug, new_slug)
                    obj.slug = new_slug
                    obj.save(update_fields=["slug"])

def backwards(apps, schema_editor):
    # No automatic backwards: restoring previous slug values should be done from
    # a database backup. This keeps the migration simple and avoids storing
    # historical values in the schema.
    return

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_0002_alter_reaction_type_0002_bookmark_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]