# Generated by Django 5.0 on 2026-05-14 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_0002_alter_reaction_type_0002_bookmark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], max_length=20)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='main.article')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', '-created_at'], name='main_articl_article_aa909d_idx'), models.Index(fields=['actor', '-created_at'], name='main_articl_actor_i_c9b27e_idx')],
            },
        ),
    ]
