import pytest
from django.utils.text import slugify
from unidecode import unidecode
from apps.main.models import Article, Category, Tag


@pytest.mark.django_db
def test_slug_generation_and_uniqueness():
    # create two articles with the same title (cyrillic) to test transliteration and uniqueness
    a1 = Article.objects.create(title="Тестовая статья", slug="")
    a2 = Article.objects.create(title="Тестовая статья", slug="")

    # emulate migration logic for slug base
    base1 = slugify(unidecode(a1.title)).strip("-") or f"item-{a1.pk}"
    base2 = slugify(unidecode(a2.title)).strip("-") or f"item-{a2.pk}"

    assert base1 != ""
    assert base2 != ""

    # ensure slugs generated by migration would be unique
    # run the same uniqueness algorithm used in migration here minimally
    slugs = set()
    for obj, base in ((a1, base1), (a2, base2)):
        candidate = base[:255]
        i = 1
        while candidate in slugs:
            suffix = f"-{i}"
            allowed = 255 - len(suffix)
            candidate = base[:allowed] + suffix
            i += 1
        slugs.add(candidate)

    assert len(slugs) == 2


@pytest.mark.django_db
def test_category_and_tag_slug_generation():
    c = Category.objects.create(name="Технологии", slug="")
    t = Tag.objects.create(name="Django Тест", slug="")

    c_base = slugify(unidecode(c.name)).strip("-") or f"item-{c.pk}"
    t_base = slugify(unidecode(t.name)).strip("-") or f"item-{t.pk}"

    assert c_base != ""
    assert t_base != ""
